DEBUG: false
ROOT_PATH: '/home/server/pyplanet'
TMP_PATH: '/home/server/pyplanet/tmp'
POOLS:
  - default
OWNERS:
  default:
    - Bgaia31IQIKwjnRVKdrsyw
    - nJNIsRdyQFSSWV054K3EGw
SELF_UPGRADE: false
DATABASES:
  default:
    ENGINE: 'peewee_async.MySQLDatabase'
    NAME: 'pyplanet'
    OPTIONS:
      host: 'database'
      user: 'pyplanet'
      password: 'pyplanet'
      charset: 'utf8mb4'
DEDICATED:
  default:
    HOST: 'server'
    PORT: '5005'
    USER: 'SuperAdmin'
    PASSWORD: 'SuperAdmin'
MAP_MATCHSETTINGS:
  default: 'maplist.txt'
BLACKLIST_FILE:
  default: 'blacklist.txt'
LOGGING_WRITE_LOGS: true
LOGGING_ROTATE_LOGS: true
LOGGING_DIRECTORY: '/home/server/pyplanet/logs'
STORAGE:
  default:
    DRIVER: 'pyplanet.core.storage.drivers.local.LocalDriver'
